### ISSUE TITLE
Upgrade scrapy-redis

### ISSUE THREAD

**Issue by younghz** [darkrho/scrapy-redis#22]
Hi darkrho,
As we all know, the newest version of `Scrapy` is 0.24.4. However, some attributions of `scrapy-redis` is based on the old version.
There are some attributions of `Scrapy` used in `scrapy-redis` has changed in the new version , Such as,    
1. Class `scrapy.contrib.loader.XPathItemLoader` was renamed to `scrapy.contrib.loader.ItemLoader`.
2. Class  `scrapy.spider.BaseSpider` was renamed to `scrapy.spider.Spider`.
3. The data structure of `ITEM_PIPELINES` was changed from `set`/`list` to `dict`.
4. Class `HtmlXpathSeletor` was changed to `Selector`.     

When we use `scrapy-redis` with `Scrapy`(new version), some warnings would appear.     
So, something could be done to upgrade 'scrapy-redis' . If it is OK, I'd like to have a _pull request_.

**Comment by darkrho** [comment]
Now `scrapy-redis` is fully compatible with latest version of Scrapy. (#36)
