### ISSUE TITLE
some error in scrapy redis

### ISSUE THREAD

**Issue by zqp821907280** [darkrho/scrapy-redis#30]
hi,when i use scrapy redis ,i found this problem:
i write two spider,the first spider parse list urls and then obtain detail url then push detail url to redis schedule,
when i run the second spider ,
i want the second spider call some function,like def start_requets(self): (this method is login method,and get cookies,after get cookies can visit detail url),this spider didn't call def start_request(self): function,this spider get detail url from redis schedule,and then this spider request detail url,and response code 302(because the second spider not cookies).

i want to call some function before my spider get url from redis schedule , after spider run these function ,this spider get url from redis schedule,then request these url.

def start_requests(self):
		url = 'http://XXXXX'

		yield FormRequest(url=url,formdata=data, callback=self.get_checkcode,dont_filter=True)

hope ,some one give me advice.

thank you .

**Comment by darkrho** [comment]
Hi, instead of storing only URLs you may want to store the serialized
request to redis. Although I'm not sure if you will need special handling
for the cookies as they are set by a middleware. This implies either
customizing the scheduler object or doing all the redis stuff in you spider.

Best,
Rolando

**Comment by zqp821907280** [comment]
hi,my tag is a big site,i have some account number(like username,password),then i use one(the first spider) account no login this site,and get detail url then push redis schedule,then use the second(the sencode spider) account no login again,but the second spider can't login(they are use the same redis key(same spider name,just different directory),and same login url ),so the second spider get detial url from redis scheduler,and get 302 response code(because the detail url need cookies can visit,the second spider not login), is there some function to make my second spider login in my spider,and then request these detail urls(from redis schedule).                                                                  thank you Rolando.

**Comment by darkrho** [comment]
Although it's likely you already found a solution for your problem, I'd suggest to customize the related classes to push a json dict with the URL and associated data (cookies, referer, etc), so you can continue the crawling in the spider.
