### ISSUE TITLE
Scrapy 1.0 version throwing Warnings

### ISSUE THREAD

**Issue by nikhilninawe** [darkrho/scrapy-redis#32]
With the new version of Scrapy, following warning is thrown. 

/Library/Python/2.7/site-packages/scrapy_redis/dupefilter.py:4: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  from scrapy.dupefilter import BaseDupeFilter

Please modify the code and push it to pypi repository.

**Comment by darkrho** [comment]
Thanks for your concerns, I will do it by the weekend.

**Comment by darkrho** [comment]
Fixed through #36
